apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
        - env:
            - name: MARIADB_DATABASE
              value: septober_prod_test_oxymoron
            - name: MARIADB_PASSWORD
              value: thisIsClearlyNotGood4Prod
            - name: MARIADB_ROOT_PASSWORD
              value: thisIsClearlyNotGood4Prod
            - name: MARIADB_USER
              value: septober_user
          image: docker.io/bitnami/mariadb:10.3-debian-10
          name: mariadb
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
status: {}
