apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: septober-dev
  name: septober-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: septober-dev
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: septober-dev
    spec:
      containers:
        - args:
            - ./entrypoint-8080.sh
          env:
            - name: MESSAGGIO_OCCASIONALE
              value: '''DockerCompose See dev in 8080 and prod in 8081 my friend with bogus MAriaDB just migrated! Dev mounts /app prod does NOT.'''
            - name: RAILS_ENV
              value: development
          image: septober-ng:latest
          name: septober-dev
          ports:
            - containerPort: 8080
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /var/www-public/septober/
              name: septober-dev-claim0
      restartPolicy: Always
      volumes:
        - name: septober-dev-claim0
          persistentVolumeClaim:
            claimName: septober-dev-claim0
status: {}
