# YAML template with dummy/guest credentials.
# Replace with personal credentials in ~/.septober.yml (do not commit!)
septober_local: 
  site: "http://localhost:8080/api/"
  user: guest
  password: guest
  description: "Local dev instance"

septober:
  site: "https://septober-mysql-2-3-12-prova-v3ydafeb7q-lm.a.run.app/api/"
  user: guest
  password: guest
  description: "Cloud Run remote instance"
