# copying from bitnami: https://hub.docker.com/r/bitnami/rails/
# I want my app to use the same vars as bitnami for further compatibility.
version: '2'
services:

  # Docs: https://hub.docker.com/r/bitnami/mariadb
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      #- ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=thisIsClearlyNotGood4Prod
      - MARIADB_USER=septober_user
      - MARIADB_PASSWORD=thisIsClearlyNotGood4Prod
      - MARIADB_DATABASE=septober_prod_test_oxymoron
    ports:
      - 3306:3306

  septober-prod:
    tty: true # Enables debugging capabilities when attached to this container.
    #image: docker.io/bitnami/rails:6-debian-10
    image: septober-ng:latest
    # Wait for MariaDB to spin up correctly before injecting DB migrations..
    command: >
     bash -c "
       sleep 10 &&
       bundle exec rake db:migrate && 
       rake db:seed && 
       ./entrypoint-8080.sh
     "
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - DATABASE_NAME=septober_prod_test_oxymoron
      - DATABASE_USER=septober_user
      - DATABASE_PASSWORD='thisIsClearlyNotGood4Prod'
      - ADMIN_PASSWORD='Ch4ngeM3Th1s1sGu3ss4ble'
      - MESSAGGIO_OCCASIONALE='DockerCompose v1.3_20201228 test to cheaply deploy a MySQL PROD config. Connect with guest // seed-guest''
      - RAILS_ENV=production
    depends_on:
      - mariadb
    ports:
      - 8081:8080
  #    volumes:
  #      - .:/app


  #dev:8080 (files are editable)
  septober-dev:
    tty: true # Enables debugging capabilities when attached to this container.
    #image: docker.io/bitnami/rails:6-debian-10
    image: septober-ng:latest
    # Wait for MariaDB to spin up correctly before injecting DB migrations..
    command: ./entrypoint-8080.sh
    environment:
      - MESSAGGIO_OCCASIONALE='DockerCompose See dev in 8080 and prod in 8081 my friend with bogus MAriaDB just migrated! Dev mounts /app prod does NOT.'
      - RAILS_ENV=development
    ports:
      - 8080:8080
    volumes:
      - .:/var/www-public/septober/