#################################
# This takes septober:v1.2 and juist injects the latest code 
# It's a sort of cheating.
#################################

FROM palladius/septober:v1.2


ADD . /septober/cat

WORKDIR /septober/


# Added for MySQL but if you only use SQLite, its ok to remove the initializer.
RUN mv ./config/initializers/abstract_mysql2_adapter.rb ./config/initializers/abstract_mysql2_adapter.rb.inutile

RUN /bin/sh /septober/dockerize/prep.sh

CMD ["rails", "server"]
