apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: septober
build:
  tagPolicy: # copied from https://skaffold.dev/docs/pipeline-stages/taggers/
    #gitCommit: {}
    dateTime:
      format: "20060102_150405"
      timezone: "Local"
  artifacts:
#  - image: gcr.io/7eptober/sk-septober-ng # palladius/sk-septober
  - image: sk-septober-ng # palladius/sk-septober
    docker:
      dockerfile: Dockerfile
    ######################################################################
    # Syncing app/ of RoR without rebuild with docker - for efficiency
    # Very powerful! Try it Riccardo
    ######################################################################
    sync:
      # infer:
      #   - app/
      manual:
      - src:  app/
        dest: app/
      - src:  config/
        dest: config/
      - src:  VERSION
        dest: VERSION
deploy:
  kubectl:
    manifests:
#    - kubernetes/skaffold-recipes/gke*.yaml
    - kubernetes/skaffold-recipes/skaffold*.yaml

# Copiato da cloud-ops-sandbox
profiles:
# "gcb" profile allows building and pushing the images
# on Google Container Builder without requiring docker
# installed on the developer machine. However, note that
# since GCB does not cache the builds, each build will
# start from scratch and therefore take a long time.
#
# This is not used by default. To use it, run:
#     skaffold run -p gcb
- name: gcb
  build:
    # explained here: https://skaffold.dev/docs/pipeline-stages/builders/
    googleCloudBuild:
      diskSizeGb: 300
      machineType: N1_HIGHCPU_32
      timeout: 3600s
      projectId: 7eptober
- name: local
  build:
    local:
      push: false
